### PR TITLE
added error messages for malformed and missing key in .harmony file to fix issue #168

### PR DESCRIPTION
**Pull request by avvalenx**
Please let me know if any more information is needed

### CODE REVIEW

**Review by stephenykp — COMMENTED** [review]
Thank you so much for your contribution, @avvalenx ! Can you add a new entry to the Unreleased section of the changelog describing your changes?

**Comment by avvalenx** [comment]
You're welcome @skorper! I added the changes to the unreleased section of the changelog. Please let me know if anything else is needed or if this was done incorrectly. Thank you.

**Comment by stephenykp** [comment]
@avvalenx Looks great, thank you! There is a conflict now, can you resolve that before I merge? Thanks again!

**Comment by avvalenx** [comment]
Yes conflict is resolved @skorper

**Comment by avvalenx** [comment]
@skorper what happened with these checks? Is this something I did wrong? I pulled from the main branch instead of development would that have an effect? Let me know if there is anything I can do to assist.

**Comment by stephenykp** [comment]
@avvalenx I think the build is failing because the secrets needed to run the regression tests are not present in your fork. I will go ahead and merge without the regression tests passing, since it's a simple enough change. Thanks again for your contribution!

**Pull request merged**
